# ninja/parallel builds disable output colors, forcing them here. global scope to
# catch all targets. cmake will have this build into 3.24
if(CMAKE_VERSION VERSION_LESS "3.24")
	option(CMAKE_COLOR_DIAGNOSTICS "Always produce ANSI-colored output" OFF)
	if(CMAKE_COLOR_DIAGNOSTICS)
		if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
			add_compile_options("-fdiagnostics-color=always")
		elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
			add_compile_options("-fcolor-diagnostics")
		endif()
	endif()
endif()

# Endianess check
if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.20)
	if(CMAKE_CXX_BYTE_ORDER STREQUAL "BIG_ENDIAN")
		set(PLAYER_BIGENDIAN 1)
	endif()
else()
	include(TestBigEndian)
	test_big_endian(PLAYER_BIGENDIAN)
endif()

# Since there are shared workarounds, add catch-all here
if(NINTENDO_WII OR NINTENDO_WIIU OR NINTENDO_3DS OR NINTENDO_SWITCH)
	set(PLAYER_DEVKITPRO 1)

	# handle debug information files
	function(player_handle_dkp_debug_files TARGET)
		dkp_target_generate_symbol_list(${TARGET})
		get_target_property(OUTDIR ${TARGET} BINARY_DIR)
		get_target_property(OUTNAME ${TARGET} OUTPUT_NAME)
		if(NOT OUTNAME)
			set(OUTNAME "${TARGET}")
		endif()
		set(OUTPUT "${OUTDIR}/${OUTNAME}")

		install(FILES ${OUTPUT}.map ${OUTPUT}.lst
			DESTINATION . COMPONENT debug)
	endfunction()
endif()
if(PLAYER_DEVKITPRO OR VITA OR PS4)
	set(PLAYER_CONSOLE_PORT 1)
endif()

# Detect a desktop macOS system
if(APPLE AND NOT IOS AND NOT CMAKE_SYSTEM_NAME STREQUAL "tvOS")
	set(PLAYER_MACOS 1)
endif()

include(GetGitRevisionDescription)
# query special files or git commands to figure out a usable version
function(player_find_gitversion)
	cmake_parse_arguments(FIND_GITVER "" "VERSION_VAR;MESSAGE_VAR" "" ${ARGN})

	# internal vars
	set(version "VERSION-NOTFOUND")
	set(message "Unknown")

	# generated by our maintainer script for release archives
	if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/builds/cmake/.git-dist)
		set(message "distribution archive")
	else()
		# git checkout or GitHub export
		# 1) try git tag
		git_get_exact_tag(GIT_TAG)
		if(GIT_TAG)
			set(message "release tag \"${GIT_TAG}\"")
		else()
			# 2) try normal checkout
			git_describe(GIT_DESCRIPTION)
			if(GIT_DESCRIPTION)
				# concatenate a version string with hash
				string(REPLACE "-" ";" GIT_DESCRIPTION ${GIT_DESCRIPTION})
				list(LENGTH GIT_DESCRIPTION GIT_DESCRIPTION_PARTS)
				if(GIT_DESCRIPTION_PARTS EQUAL 3)
					list(GET GIT_DESCRIPTION 0 GIT_TAG)
					list(GET GIT_DESCRIPTION 1 GIT_COMMITS)
					list(GET GIT_DESCRIPTION 2 GIT_HASH)
					set(message "${GIT_COMMITS} commits since tag \"${GIT_TAG}\", ")
					string(PREPEND GIT_COMMITS "+")
					string(SUBSTRING ${GIT_HASH} 1 -1 GIT_HASH) # strip the g prefix
				else()
					# no tags found, only hash (checkout without history/detached head)
					list(GET GIT_DESCRIPTION 0 GIT_HASH)
					set(message "")
				endif()
				set(version "git${GIT_COMMITS}@${GIT_HASH}")
				string(APPEND message "object hash is ${GIT_HASH}")

				# append marker for local changes
				git_local_changes(GIT_DIRTY)
				if(GIT_DIRTY STREQUAL "DIRTY")
					string(APPEND version "-dirty")
					string(APPEND message ", you have uncommitted changes")
				endif()
			else()
				# 3) no git dir, likely git archive export from GitHub
				file(STRINGS ${CMAKE_CURRENT_SOURCE_DIR}/builds/cmake/.git-hash
					GIT_HASH_STRINGS REGEX "^[A-Za-z0-9_]+$" LIMIT_COUNT 1)
				list(LENGTH GIT_HASH_STRINGS GIT_HASH_STRINGS_LENGTH)
				if(GIT_HASH_STRINGS_LENGTH EQUAL 1)
					list(GET GIT_HASH_STRINGS 0 GIT_HASH)
					set(version "git@${GIT_HASH}")
					set(message "object hash is ${GIT_HASH}")
				else()
					# 4) give up, use "undefined" values
				endif()
			endif()
		endif()
	endif()

	# export information
	if(FIND_GITVER_VERSION_VAR)
		set(${FIND_GITVER_VERSION_VAR} ${version} PARENT_SCOPE)
	endif()
	if(FIND_GITVER_MESSAGE_VAR)
		set(${FIND_GITVER_MESSAGE_VAR} ${message} PARENT_SCOPE)
	endif()
endfunction()

# Helper function for the feature summary to unpack a library list
function(player_summary_list PREFIX LIST_VAR)
	list(LENGTH LIST_VAR ENTRIES)
	if(ENTRIES GREATER_EQUAL 1)
		list(JOIN ${LIST_VAR} ", " LIST)
		message(STATUS "${PREFIX}: ${LIST}")
	else()
		message(STATUS "${PREFIX}: No")
	endif()
endfunction()

# Show feature status based on condition(s)
# (same technique and behaviour as CMakeDependentOption on cmake<3.22)
# Condition handling could be improved with a loop to support more than 2
function(player_summary_line PREFIX CONDITION1 FEATURE1)
	if(ARGC GREATER 6)
		message(AUTHOR_WARNING "Invalid use of internal function")
	endif()

	# handle first condition
	set(CONDITION1_OK 1)
	foreach(d ${CONDITION1})
		string(REGEX REPLACE " +" ";" FEATURE_DEP "${d}")
		if(${FEATURE_DEP})
		else()
			set(CONDITION1_OK 0)
		endif()
	endforeach()

	# handle optional second condition
	set(CONDITION2_OK 0)
	if(ARGC GREATER_EQUAL 5)
		set(FEATURE2 ${ARGV4})
		set(CONDITION2_OK 1)
		foreach(d ${ARGV3})
			string(REGEX REPLACE " +" ";" FEATURE_DEP "${d}")
			if(${FEATURE_DEP})
			else()
				set(CONDITION2_OK 0)
			endif()
		endforeach()
	endif()

	# default status
	set(DEFAULT "No")
	if(ARGC EQUAL 6)
		set(DEFAULT ${ARGV5})
	elseif(ARGC EQUAL 4)
		set(DEFAULT ${ARGV3})
	endif()

	if(CONDITION1_OK)
		message(STATUS "${PREFIX}: ${FEATURE1}")
	elseif(CONDITION2_OK)
		message(STATUS "${PREFIX}: ${FEATURE2}")
	else()
		message(STATUS "${PREFIX}: ${DEFAULT}")
	endif()
endfunction()
