# This contains all source files part of the main engine,
# to use the player as library without platform bindings.

add_subdirectory(game)
add_subdirectory(scene)
add_subdirectory(window)

target_sources(${PROJECT_NAME} PRIVATE
	lcf_data.cpp
	lcf/data.h
	async_handler.cpp
	async_handler.h
	async_op.h
	algo.h
	algo.cpp
	attribute.h
	attribute.cpp
	autobattle.cpp
	autobattle.h
	background.cpp
	background.h
	baseui.cpp
	baseui.h
	battle_animation.cpp
	battle_animation.h
	bitmap.cpp
	bitmapfont.h
	bitmapfont_glyph.h
	bitmap.h
	bitmap_hslrgb.h
	cache.cpp
	cache.h
	callback.h
	cmdline_parser.cpp
	cmdline_parser.h
	color.h
	compiler.h
	config_param.h
	default_graphics.h
	directory_tree.cpp
	directory_tree.h
	docmain.h
	drawable.cpp
	drawable.h
	drawable_list.cpp
	drawable_list.h
	drawable_mgr.cpp
	drawable_mgr.h
	dynrpg_easyrpg.cpp
	dynrpg_easyrpg.h
	dynrpg_textplugin.cpp
	dynrpg_textplugin.h
	enemyai.cpp
	enemyai.h
	exe_reader.cpp
	exe_reader.h
	exfont.h
	feature.cpp
	feature.h
	filefinder.cpp
	filefinder.h
	filefinder_rtp.cpp
	filefinder_rtp.h
	fileext_guesser.cpp
	fileext_guesser.h
	filesystem.cpp
	filesystem.h
	filesystem_hook.cpp
	filesystem_hook.h
	filesystem_lzh.cpp
	filesystem_lzh.h
	filesystem_native.cpp
	filesystem_native.h
	filesystem_root.cpp
	filesystem_root.h
	filesystem_stream.cpp
	filesystem_stream.h
	filesystem_zip.cpp
	filesystem_zip.h
	filesystem_tar.cpp
	filesystem_tar.h
	flash.h
	flat_map.h
	font.cpp
	font.h
	fps_overlay.cpp
	fps_overlay.h
	frame.cpp
	frame.h
	generated/bitmapfont_baekmuk.h
	generated/bitmapfont_rmg2000.h
	generated/bitmapfont_ttyp0.h
	generated/bitmapfont_wqy.h
	generated/logo.h
	generated/logo2.h
	generated/shinonome_gothic.h
	generated/shinonome_mincho.h
	graphics.cpp
	graphics.h
	hslrgb.cpp
	hslrgb.h
	icon.h
	image_bmp.cpp
	image_bmp.h
	image_png.cpp
	image_png.h
	image_xyz.cpp
	image_xyz.h
	input_buttons.h
	input.cpp
	input.h
	input_source.cpp
	input_source.h
	instrumentation.cpp
	instrumentation.h
	json_helper.cpp
	json_helper.h
	keys.h
	main_data.cpp
	main_data.h
	maniac_patch.cpp
	maniac_patch.h
	map_data.h
	memory_management.h
	message_overlay.cpp
	message_overlay.h
	meta.cpp
	meta.h
	opacity.h
	options.h
	output.cpp
	output.h
	pending_message.h
	pending_message.cpp
	pixel_format.h
	pixman_image_ptr.h
	plane.cpp
	plane.h
	platform.cpp
	platform.h
	platform/clock.h
	player_main.cpp
	player_main.h
	point.h
	rand.cpp
	rand.h
	rect.cpp
	rect.h
	registry.h
	registry_wine.cpp
	rtp.cpp
	rtp.h
	rtp_table.cpp
	scene.cpp
	scene.h
	screen.cpp
	screen.h
	shake.h
	span.h
	sprite_airshipshadow.cpp
	sprite_airshipshadow.h
	sprite_actor.cpp
	sprite_actor.h
	sprite_battler.cpp
	sprite_battler.h
	sprite_enemy.cpp
	sprite_enemy.h
	sprite_character.cpp
	sprite_character.h
	sprite_picture.h
	sprite_picture.cpp
	sprite_weapon.cpp
	sprite_weapon.h
	sprite.cpp
	sprite.h
	spriteset_battle.cpp
	spriteset_battle.h
	spriteset_map.cpp
	spriteset_map.h
	sprite_timer.cpp
	sprite_timer.h
	state.cpp
	state.h
	std_clock.h
	string_view.cpp
	string_view.h
	system.h
	teleport_target.h
	text.cpp
	text.h
	tilemap.cpp
	tilemap.h
	tilemap_layer.cpp
	tilemap_layer.h
	tone.h
	transform.h
	transition.cpp
	transition.h
	translation.cpp
	translation.h
	util_macro.h
	utils.cpp
	utils.h
	version.cpp
	version.h
	weather.cpp
	weather.h
	window.cpp
	window.h)
